name: epi2melabs-wf-transcriptomes
channels:
    - epi2melabs
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python==3.8.*
    - bokeh==2.4.3
    - aplanat>=0.6.15
    - epi2melabs
    - minimap2==2.24
    - samtools==1.14
    - bedtools==2.30.0
    - pychopper>=2.7.0
    - pandas==1.3.5
    - gffread==0.12.7
    - gffcompare==0.11.2
    - gffutils==0.10.1
    - seqkit==2.2.0
    - stringtie==2.1.1
    - curl
    - pysam==0.17.0
    - racon==1.4.20
    - spoa==3.4.0
    - fastcat==0.4.10
    - isonclust2==2.3
    - parallel
    - scikit-learn==1.0.2
    - natsort
# Fusion detection dependencies
#    - bpipe=0.9.9.2
    - java-jdk
    - r-base
    - gxx
# Differential expression dependencies
    - bioconductor-genomicfeatures
    - bioconductor-drimseq
    - bioconductor-edger
    - bioconductor-dexseq
    - bioconductor-stager
    - r-dplyr
    - r-tidyr
    - salmon==1.9.0